// ═══════════════════════════════════════════════════════════
// CUT LIBRARY — Biblioteca completa de cortes
// ═══════════════════════════════════════════════════════════

export const CUT_LIBRARY = [
  {
    id: 'one-length',
    name: 'One Length',
    elevation: 0,
    projection: 'Natural',
    distribution: 'Uniforme',
    weight: 'Máximo',
    section: 'Horizontal',
    guide: 'Estacionária',
    connection: 'Conectado',
    movement: 'Mínimo',
    volume: 'Baixo',
    color: '#B44DFF',
    guideType: 'horizontal',
    sliceType: 'parallel',
    sliceCount: 5,
    camera: 'back',
    steps: [
      'Divide o cabelo em 4 quadrantes com repartição central e lateral.',
      'Inicia na nuca — guia estacionária horizontal no comprimento desejado.',
      '0° de elevação — sem levantar o cabelo do couro cabeludo.',
      'Sobe seção por seção mantendo a mesma guia horizontal.',
      'Verifica a linha de peso na visão posterior — deve ser perfeitamente horizontal.',
    ],
    tech: [
      { key: 'Elevação',    val: '0°'           },
      { key: 'Projeção',    val: 'Natural'       },
      { key: 'Distribuição',val: 'Uniforme'      },
      { key: 'Guia',        val: 'Estacionária'  },
      { key: 'Seção',       val: 'Horizontal'    },
      { key: 'Peso',        val: 'Máximo'        },
    ],
  },
  {
    id: 'graduation',
    name: 'Graduação',
    elevation: 45,
    projection: 'Perpendicular',
    distribution: 'Uniforme',
    weight: 'Acumulado',
    section: 'Horizontal',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Médio',
    volume: 'Médio',
    color: '#FF7A4D',
    guideType: 'horizontal',
    sliceType: 'parallel',
    sliceCount: 6,
    camera: 'back',
    steps: [
      'Base na nuca — guia estacionária no comprimento final desejado.',
      'Elevação crescente de 0° a 45° — cria linha de peso acumulada.',
      'Seções horizontais finas — sobe progressivamente.',
      'Linha de peso visível define o "stacked" na nuca.',
      'Verifica peso e equilíbrio nas vistas laterais.',
    ],
    tech: [
      { key: 'Elevação',    val: '45°'           },
      { key: 'Projeção',    val: 'Diagonal'      },
      { key: 'Distribuição',val: 'Uniforme'      },
      { key: 'Guia',        val: 'Viajante'      },
      { key: 'Seção',       val: 'Horizontal'    },
      { key: 'Peso',        val: 'Acumulado'     },
    ],
  },
  {
    id: 'layer-90',
    name: 'Layer 90°',
    elevation: 90,
    projection: 'Perpendicular',
    distribution: 'Uniforme',
    weight: 'Removido',
    section: 'Radial',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Alto',
    volume: 'Alto',
    color: '#4D9FFF',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 7,
    camera: 'top',
    steps: [
      'Apex como ponto central — partição radial a partir do topo.',
      '90° de elevação perpendicular ao couro cabeludo.',
      'Guia viajante — cada mecha guia a próxima.',
      'Distribui uniformemente por toda a cabeça.',
      'Verifica cantos no ridge parietal — sem peso acumulado.',
    ],
    tech: [
      { key: 'Elevação',    val: '90°'           },
      { key: 'Projeção',    val: 'Perpendicular' },
      { key: 'Distribuição',val: 'Uniforme'      },
      { key: 'Guia',        val: 'Viajante'      },
      { key: 'Seção',       val: 'Radial'        },
      { key: 'Peso',        val: 'Removido'      },
    ],
  },
  {
    id: 'layer-135',
    name: 'Layer 135°',
    elevation: 135,
    projection: 'Over-directed',
    distribution: 'Uniforme',
    weight: 'Removido',
    section: 'Radial',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Máximo',
    volume: 'Alto',
    color: '#FF4DFF',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 7,
    camera: 'top',
    steps: [
      'Apex como origem — over-direction intencional.',
      '135° de elevação além da perpendicular — long layers.',
      'Cria movimento e textura máxima no comprimento.',
      'Ideal para cabelos médios e longos com desejo de volume.',
      'Verifica a queda natural — deve haver leveza e movimento.',
    ],
    tech: [
      { key: 'Elevação',    val: '135°'          },
      { key: 'Projeção',    val: 'Over-directed' },
      { key: 'Distribuição',val: 'Uniforme'      },
      { key: 'Guia',        val: 'Viajante'      },
      { key: 'Seção',       val: 'Radial'        },
      { key: 'Peso',        val: 'Removido'      },
    ],
  },
  {
    id: 'flow',
    name: 'Flow',
    elevation: 45,
    projection: 'Natural',
    distribution: 'Uniforme',
    weight: 'Médio',
    section: 'Radial',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Alto',
    volume: 'Médio',
    color: '#C8A96E',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 8,
    camera: 'front',
    steps: [
      'Divisão central — repartição ao meio partindo do apex.',
      'Seções radiais saindo do topo com elevação de 45°.',
      'Slip cut nas pontas para criar textura e leveza.',
      'Conecta lateral com topo usando guia interna.',
      'Seca naturalmente — verifica queda e fluidez do movimento.',
    ],
    tech: [
      { key: 'Elevação',    val: '45°'          },
      { key: 'Projeção',    val: 'Natural'      },
      { key: 'Distribuição',val: 'Uniforme'     },
      { key: 'Guia',        val: 'Viajante'     },
      { key: 'Seção',       val: 'Radial'       },
      { key: 'Peso',        val: 'Médio'        },
    ],
  },
  {
    id: 'curtain',
    name: 'Curtain',
    elevation: 45,
    projection: 'Natural',
    distribution: 'Uniforme',
    weight: 'Médio',
    section: 'Radial',
    guide: 'Estacionária',
    connection: 'Conectado',
    movement: 'Alto',
    volume: 'Médio',
    color: '#C8A96E',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 8,
    camera: 'front',
    steps: [
      'Franja central dividida ao meio — ponto de origem no apex.',
      'Seções radiais a partir da divisão central.',
      'Elevação de 45° — mantém comprimento com leveza.',
      'Lateral conectada ao topo com ângulo suave.',
      'Finaliza com texturas nas pontas para efeito cortina.',
    ],
    tech: [
      { key: 'Elevação',    val: '45°'          },
      { key: 'Projeção',    val: 'Natural'      },
      { key: 'Distribuição',val: 'Uniforme'     },
      { key: 'Guia',        val: 'Estacionária' },
      { key: 'Seção',       val: 'Radial'       },
      { key: 'Franja',      val: 'Central'      },
    ],
  },
  {
    id: 'wolf',
    name: 'Wolf Cut',
    elevation: 90,
    projection: 'Perpendicular',
    distribution: 'Uniforme',
    weight: 'Texturizado',
    section: 'Radial',
    guide: 'Viajante',
    connection: 'Desconectado',
    movement: 'Máximo',
    volume: 'Alto',
    color: '#FF4DFF',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 9,
    camera: 'front',
    steps: [
      'Topo: seções radiais a 90° do apex — cria volume máximo.',
      'Laterais: elevação 45° — cria camadas visíveis.',
      'Franja: 0° sobre a testa — desconectada do resto.',
      'Slip cut agressivo em todo o comprimento para textura shaggy.',
      'Verifica o "wolf" — volume no topo, peso nas pontas.',
    ],
    tech: [
      { key: 'Elevação',    val: '90° / 45°'    },
      { key: 'Projeção',    val: 'Perpendicular'},
      { key: 'Distribuição',val: 'Uniforme'     },
      { key: 'Conexão',     val: 'Desconectado' },
      { key: 'Seção',       val: 'Radial'       },
      { key: 'Textura',     val: 'Máxima'       },
    ],
  },
  {
    id: 'mullet',
    name: 'Mullet',
    elevation: 0,
    projection: 'Natural',
    distribution: 'Desconectada',
    weight: 'Acumulado',
    section: 'Horizontal',
    guide: 'Estacionária',
    connection: 'Desconectado',
    movement: 'Médio',
    volume: 'Baixo',
    color: '#FF7A4D',
    guideType: 'horizontal',
    sliceType: 'parallel',
    sliceCount: 4,
    camera: 'back',
    steps: [
      'Define linha de corte frontal — curto sobre a testa.',
      'Laterais: cortadas curtas até a orelha, 0° de elevação.',
      'Posterior: mantido longo — guia estacionária baixa.',
      'Transição na região occipital — desconectada intencionalmente.',
      'Verifica o "business in front, party in back".',
    ],
    tech: [
      { key: 'Elevação',    val: '0°'           },
      { key: 'Frontal',     val: 'Curto'        },
      { key: 'Posterior',   val: 'Longo'        },
      { key: 'Conexão',     val: 'Desconectado' },
      { key: 'Seção',       val: 'Horizontal'   },
      { key: 'Transição',   val: 'Abrupta'      },
    ],
  },
  {
    id: 'pompadour',
    name: 'Pompadour',
    elevation: 90,
    projection: 'Perpendicular',
    distribution: 'Direcionada',
    weight: 'Topo',
    section: 'Diagonal ant.',
    guide: 'Estacionária',
    connection: 'Desconectado',
    movement: 'Mínimo',
    volume: 'Alto topo',
    color: '#FFD04D',
    guideType: 'diagonal-fwd',
    sliceType: 'parallel',
    sliceCount: 5,
    camera: 'side-right',
    steps: [
      'Laterais: fade ou taper baixo — máquina ou tesoura sobre pente.',
      'Topo: seção frontal a posterior — over-direction para frente.',
      'Elevação 90° no topo — cria volume e altura.',
      'Guia direcionada para cima e para frente (pompadour sweep).',
      'Finaliza com produto — seca com o secador para cima.',
    ],
    tech: [
      { key: 'Elevação',    val: '90°'          },
      { key: 'Direção',     val: 'Para frente'  },
      { key: 'Lateral',     val: 'Fade/Taper'   },
      { key: 'Conexão',     val: 'Desconectado' },
      { key: 'Volume',      val: 'Alto / Topo'  },
      { key: 'Produto',     val: 'Necessário'   },
    ],
  },
  {
    id: 'french-crop',
    name: 'French Crop',
    elevation: 0,
    projection: 'Natural',
    distribution: 'Uniforme',
    weight: 'Franja',
    section: 'Horizontal',
    guide: 'Estacionária',
    connection: 'Desconectado',
    movement: 'Baixo',
    volume: 'Baixo',
    color: '#4D9FFF',
    guideType: 'horizontal',
    sliceType: 'parallel',
    sliceCount: 4,
    camera: 'front',
    steps: [
      'Laterais e nuca: fade alto ou taper — base limpa.',
      'Topo: seções horizontais, 0° de elevação.',
      'Franja: corte reto horizontal sobre a testa — guia frontal.',
      'Textura nas pontas com tesoura — cria efeito "cropped".',
      'Verifica a franja — deve cair reta e horizontal.',
    ],
    tech: [
      { key: 'Elevação',    val: '0°'           },
      { key: 'Franja',      val: 'Reta / Raso'  },
      { key: 'Lateral',     val: 'Fade'         },
      { key: 'Seção',       val: 'Horizontal'   },
      { key: 'Conexão',     val: 'Desconectado' },
      { key: 'Textura',     val: 'Pontas'       },
    ],
  },
  {
    id: 'textured-crop',
    name: 'Textured Crop',
    elevation: 45,
    projection: 'Diagonal',
    distribution: 'Uniforme',
    weight: 'Texturizado',
    section: 'Horizontal',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Médio',
    volume: 'Médio',
    color: '#50E090',
    guideType: 'horizontal',
    sliceType: 'parallel',
    sliceCount: 5,
    camera: 'front',
    steps: [
      'Lateral: fade ou taper — base limpa.',
      'Topo: seções horizontais com elevação de 45°.',
      'Point cut agressivo — cria textura e movimento no topo.',
      'Franja: texturizada com point cut — sem linha reta definida.',
      'Verifica textura no seco — deve haver movimento natural.',
    ],
    tech: [
      { key: 'Elevação',    val: '45°'          },
      { key: 'Técnica',     val: 'Point cut'    },
      { key: 'Franja',      val: 'Texturizada'  },
      { key: 'Lateral',     val: 'Fade'         },
      { key: 'Seção',       val: 'Horizontal'   },
      { key: 'Textura',     val: 'Alta'         },
    ],
  },
  {
    id: 'disconnected',
    name: 'Disconnected',
    elevation: 90,
    projection: 'Perpendicular',
    distribution: 'Desconectada',
    weight: 'Topo',
    section: 'Radial',
    guide: 'Estacionária',
    connection: 'Desconectado',
    movement: 'Alto',
    volume: 'Alto',
    color: '#FF4D4D',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 6,
    camera: 'side-right',
    steps: [
      'Lateral: fade zero — contraste máximo.',
      'Topo: seções radiais, 90° de elevação — volume total.',
      'Sem conexão entre lateral e topo — desconexão intencional.',
      'Linha de desconexão bem definida na região parietal.',
      'Verifica o contraste — lateral vs topo deve ser dramático.',
    ],
    tech: [
      { key: 'Elevação',    val: '90°'          },
      { key: 'Lateral',     val: 'Fade zero'    },
      { key: 'Conexão',     val: 'Nenhuma'      },
      { key: 'Contraste',   val: 'Máximo'       },
      { key: 'Seção',       val: 'Radial'       },
      { key: 'Volume',      val: 'Alto / Topo'  },
    ],
  },
  {
    id: 'long-layer',
    name: 'Long Layer',
    elevation: 135,
    projection: 'Over-directed',
    distribution: 'Uniforme',
    weight: 'Removido',
    section: 'Radial',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Máximo',
    volume: 'Alto',
    color: '#C8A96E',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 7,
    camera: 'top',
    steps: [
      'Apex como centro — partição radial completa.',
      '135° de over-direction — cria long layers com leveza.',
      'Guia viajante — mecha a mecha de forma uniforme.',
      'Slip cut nas pontas para adicionar textura ao comprimento.',
      'Verifica o movimento — deve haver fluidez no comprimento.',
    ],
    tech: [
      { key: 'Elevação',    val: '135°'         },
      { key: 'Projeção',    val: 'Over-directed'},
      { key: 'Guia',        val: 'Viajante'     },
      { key: 'Seção',       val: 'Radial'       },
      { key: 'Comprimento', val: 'Mantido'      },
      { key: 'Textura',     val: 'Slip cut'     },
    ],
  },
  {
    id: 'round-layer',
    name: 'Round Layer',
    elevation: 90,
    projection: 'Perpendicular',
    distribution: 'Circular',
    weight: 'Removido',
    section: 'Pivô',
    guide: 'Estacionária',
    connection: 'Conectado',
    movement: 'Alto',
    volume: 'Alto',
    color: '#FF7A4D',
    guideType: 'pivot',
    sliceType: 'radial',
    sliceCount: 8,
    camera: 'top',
    steps: [
      'Cria guia central no apex — comprimento interno.',
      'Seções em pivô — radiais completas 360° ao redor.',
      '90° de elevação — todas as mechas para o mesmo ponto.',
      'Cria forma redonda — mais curto no centro, mais longo nas bordas.',
      'Verifica a silhueta — deve ser perfeitamente circular.',
    ],
    tech: [
      { key: 'Elevação',    val: '90°'          },
      { key: 'Seção',       val: 'Pivô 360°'   },
      { key: 'Forma',       val: 'Circular'     },
      { key: 'Guia',        val: 'Central'      },
      { key: 'Distribuição',val: 'Circular'     },
      { key: 'Volume',      val: 'Máximo'       },
    ],
  },
  {
    id: 'bro-flow',
    name: 'Bro Flow',
    elevation: 45,
    projection: 'Natural',
    distribution: 'Uniforme',
    weight: 'Médio',
    section: 'Radial',
    guide: 'Viajante',
    connection: 'Conectado',
    movement: 'Alto',
    volume: 'Médio',
    color: '#C8A96E',
    guideType: 'radial',
    sliceType: 'radial',
    sliceCount: 7,
    camera: 'side-right',
    steps: [
      'Mantém comprimento — foco em peso e movimento.',
      'Seções radiais com 45° de elevação — suaviza o volume.',
      'Sem franja definida — cabelo para o lado ou para trás.',
      'Tesoura deslizante (slide cut) para integrar camadas.',
      'Verifica o flow — deve cair naturalmente para os lados.',
    ],
    tech: [
      { key: 'Elevação',    val: '45°'          },
      { key: 'Técnica',     val: 'Slide cut'    },
      { key: 'Comprimento', val: 'Médio-longo'  },
      { key: 'Movimento',   val: 'Alto'         },
      { key: 'Seção',       val: 'Radial'       },
      { key: 'Franja',      val: 'Ausente'      },
    ],
  },
];

export function getCutById(id) {
  return CUT_LIBRARY.find(c => c.id === id) || CUT_LIBRARY[0];
}
